export enum RedisCachingEnum {
    LATEST_MATCH_PRICE = 'LATEST_MATCH_PRICE',
    LATEST_INDEX = 'LATEST_INDEX',
    LATEST_BID_ASK = 'LATEST_BID_ASK',
    LATEST_PUT_THROUGH = 'LATEST_PUT_THROUGH',
    LISTING_INFO = 'LISTING_INFO',
    SYMBOLS_GROUPS = 'SYMBOLS_GROUPS',
    LATEST_YAHOO_FINANCE_DATA = 'LATEST_YAHOO_FINANCE_DATA'
}